name: Go test and build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'
      - run: go version
